### ISSUE TITLE
Failed to init client for PD cluster

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [tikv/client-java#227]
**Describe the bug**
```
Exception in thread "main" java.lang.NullPointerException: Failed to init client for PD cluster.
	at org.tikv.shade.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:906)
	at org.tikv.common.PDClient.initCluster(PDClient.java:583)
	at org.tikv.common.PDClient.<init>(PDClient.java:115)
	at org.tikv.common.PDClient.createRaw(PDClient.java:125)
	at org.tikv.common.TiSession.<init>(TiSession.java:79)
	at org.tikv.common.TiSession.create(TiSession.java:90)
	at cn.bestsign.binlogstream.tidb.coordinator.grpc.GrpcService.<init>(GrpcService.java:39)
	at cn.bestsign.binlogstream.tidb.coordinator.grpc.GrpcProvider.<init>(GrpcProvider.java:26)
	at cn.bestsign.binlogstream.tidb.coordinator.grpc.GrpcProvider.<init>(GrpcProvider.java:37)
	at cn.bestsign.conplextables.TestTime$.main(TestTime.scala:14)
	at cn.bestsign.conplextables.TestTime.main(TestTime.scala)

```

**What did you do**
When I execute `TiSession.create(conf)`, I always face exception.

**What do you expect**
I expect to init client for PD cluster successfully. I am not sure this exception is caused by grpc.

**Java Client and TiDB/TiKV version info**
Java Client Version:     3.2.0-SNAPSHOT
idea environment:  Mac OSX               java8

Any help will be appreciated!

**Comment by marsishandsome** [comment]
please  provide  the test code

**Comment by marsishandsome** [comment]
please  provide  the test code

**Comment by ZhiXingHeYiApple** [comment]
@marsishandsome 
The test code is below:

```java
import cn.bestsign.binlogstream.tidb.coordinator.grpc.GrpcProvider
import org.tikv.common.{TiConfiguration}

object TestTime extends  App {
  override def main(args: Array[String]): Unit = {
    val conf = TiConfiguration.createDefault("10.128.32.115:2379")
    try {
      val coordinator = new GrpcProvider(conf).createCoordinator()
      coordinator.openTransaction(0)
    } catch {
      case e:Exception =>
        e.printStackTrace()
    }
  }
}
```

**GrpcService.java**
```java
package cn.bestsign.binlogstream.tidb.coordinator.grpc;

import cn.bestsign.binlogstream.tidb.coordinator.ImmutableTransaction;
import cn.bestsign.binlogstream.tidb.coordinator.Transaction;
import cn.bestsign.tidb.source.coordinator.grpc.Coordinator.TxnRequest;
import cn.bestsign.tidb.source.coordinator.grpc.Coordinator.TxnResponse;
import cn.bestsign.tidb.source.coordinator.grpc.CoordinatorServiceGrpc;
import com.google.common.base.Preconditions;
import com.google.protobuf.ByteString;
import io.grpc.stub.StreamObserver;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.tikv.common.TiConfiguration;
import org.tikv.common.TiSession;
import org.tikv.common.meta.TiTimestamp;
import org.tikv.common.util.ConcreteBackOffer;
import org.tikv.txn.TwoPhaseCommitter;

import java.util.Iterator;
import java.util.LinkedHashMap;

class GrpcService extends CoordinatorServiceGrpc.CoordinatorServiceImplBase
    implements AutoCloseable {
  private static Logger logger = LoggerFactory.getLogger(GrpcService.class);

  private static byte[] EMPTY_VALUE = new byte[0];
  private static long TXN_TTL_MS = 20000;

  static final int RETAIN_TXNS = 100;

  private final LinkedHashMap<Long, TransactionHolder> transactions = new LinkedHashMap<>();
  private final TiSession tiSession;

  GrpcService(final TiSession session) {
    this.tiSession = session;
  }

  GrpcService(final TiConfiguration conf) {
    this(TiSession.create(conf));
  }

  protected Transaction openTransaction(final long checkpointId) {
    logger.info("open transaction: {}", checkpointId);
    synchronized (transactions) {
      final TransactionHolder holder =
          transactions.computeIfAbsent(checkpointId, (id) -> new TransactionHolder());
      trimTransactions();
      synchronized (holder) {
        if (holder.getTxn() == null) {
          holder.setTxn(
              ImmutableTransaction.builder()
                  .checkpointId(checkpointId)
                  .startTs(getTimestamp())
                  .build());
          return holder.getTxn();
        } else if (holder.getTxn().isNew()) {
          return holder.getTxn();
        } else {
          throw new IllegalStateException("Illegal transaction state");
        }
      }
    }
  }

  protected Transaction prewriteTransaction(final long checkpointId, final long tableId) {
    logger.info("prewrite transaction: {}, tableId: {}", checkpointId, tableId);
    final TransactionHolder holder = transactions.get(checkpointId);
    Preconditions.checkNotNull(holder, "Transaction not found");

    final Transaction txn = holder.getTxn();
    if (txn.isPrewriting()) {
      return txn;
    }

    synchronized (holder) {
      Preconditions.checkState(holder.getTxn().isNew(), "Transaction status should be NEW");
      final byte[] pk = GrpcCommitKey.encode(tableId, txn.getCheckpointId(), txn.getStartTs());
      prewritePrimaryKey(pk, holder.getCommitter());
      holder.setTxn(
          ImmutableTransaction.builder()
              .from(holder.getTxn())
              .primaryKey(pk)
              .status(Transaction.Status.PREWRITE)
              .build());
      return holder.getTxn();
    }
  }

  protected Transaction commitTransaction(final long checkpointId) {
    logger.info("commit transaction: {}", checkpointId);
    final TransactionHolder holder = transactions.get(checkpointId);
    Preconditions.checkNotNull(holder, "Transaction not found");

    synchronized (holder) {
      if (holder.getTxn().isCommitted()) {
        logger.info("transaction already committed: {}", checkpointId);
        return holder.getTxn();
      }

      if (holder.getTxn().isNew()) {
        // No prewrite has done. just return committed status
        holder.setTxn(
            ImmutableTransaction.builder()
                .from(holder.getTxn())
                .status(Transaction.Status.COMMITTED)
                .commitTs(getTimestamp())
                .build());
        logger.info("new transaction committed: {}", checkpointId);
        return holder.getTxn();
      }

      synchronized (transactions) {
        for (final TransactionHolder h : transactions.values()) {
          if (h != holder) {
            Preconditions.checkState(
                h.getTxn().isTerminated(),
                "Transaction started before this transaction must be terminated first");
          } else {
            break;
          }
        }
        trimTransactions();
      }
      final long commitTs = getTimestamp();
      commitPrimaryKey(holder.getTxn().getPrimaryKey(), commitTs, holder.getCommitter());

      holder.setTxn(
          ImmutableTransaction.builder()
              .from(holder.getTxn())
              .commitTs(commitTs)
              .status(Transaction.Status.COMMITTED)
              .build());

      logger.info("transaction committed: {}", holder.getTxn());
      return holder.getTxn();
    }
  }

  protected Transaction abortTransaction(final long checkpointId) {
    logger.info("abort transaction: {}", checkpointId);
    final TransactionHolder holder = transactions.get(checkpointId);
    if (holder == null) {
      // fail silently for unknown transactions
      return ImmutableTransaction.builder().checkpointId(checkpointId).build();
    }

    final Transaction txn = holder.getTxn();
    if (txn.isAborted()) {
      return txn;
    }

    synchronized (holder) {
      Preconditions.checkState(!holder.getTxn().isCommitted(), "Transaction is already committed");
      abortPrimaryKey(holder.getTxn().getPrimaryKey(), holder.getCommitter());
      holder.setTxn(
          ImmutableTransaction.builder()
              .from(holder.getTxn())
              .status(Transaction.Status.ABORTED)
              .build());
      return holder.getTxn();
    }
  }

  protected Transaction getTransaction(final long checkpointId) {
    final TransactionHolder holder = transactions.get(checkpointId);
    Preconditions.checkNotNull(holder, "Transaction not found");
    return holder.getTxn();
  }

  private long getTimestamp() {
    final TiTimestamp ts = tiSession.getTimestamp();
    return ts.getVersion();
  }

  private void prewritePrimaryKey(final byte[] primaryKey, final TwoPhaseCommitter committer) {
    committer.prewritePrimaryKey(ConcreteBackOffer.newRawKVBackOff(), primaryKey, EMPTY_VALUE);
  }

  private void commitPrimaryKey(
      final byte[] primaryKey, final long commitTs, final TwoPhaseCommitter committer) {
    committer.commitPrimaryKey(ConcreteBackOffer.newRawKVBackOff(), primaryKey, commitTs);
  }

  private void abortPrimaryKey(final byte[] primaryKey, final TwoPhaseCommitter committer) {
    // TODO: implement this
  }

  private void trimTransactions() {
    synchronized (transactions) {
      final Iterator<TransactionHolder> iter = transactions.values().iterator();
      while (transactions.size() > RETAIN_TXNS && iter.hasNext()) {
        final Transaction txn = iter.next().getTxn();
        if (txn.isTerminated()) {
          iter.remove();
        } else {
          return;
        }
      }
    }
  }

  public TxnResponse transactionToResponse(final Transaction txn) {
    final TxnResponse.Builder builder =
        TxnResponse.newBuilder()
            .setCheckpointId(txn.getCheckpointId())
            .setStartTs(txn.getStartTs());

    switch (txn.getStatus()) {
      case COMMITTED:
        builder.setCommitTs(txn.getCommitTs());
      case PREWRITE:
        builder.setPrimaryKey(ByteString.copyFrom(txn.getPrimaryKey()));
      default:
        builder.setStatus(convertStatus(txn.getStatus()));
    }

    return builder.build();
  }

  public TxnResponse.Status convertStatus(final Transaction.Status status) {
    switch (status) {
      case ABORTED:
        return TxnResponse.Status.ABORTED;
      case COMMITTED:
        return TxnResponse.Status.COMMITTED;
      case NEW:
        return TxnResponse.Status.NEW;
      case PREWRITE:
        return TxnResponse.Status.PREWRITE;
      default:
        throw new UnsupportedOperationException("Unknown status: " + status.toString());
    }
  }

  @Override
  public void transactions(
      final TxnRequest request, final StreamObserver<TxnResponse> responseObserver) {
    try {
      switch (request.getAction()) {
        case OPEN:
          responseObserver.onNext(
              transactionToResponse(openTransaction(request.getCheckpointId())));
          break;
        case PREWRITE:
          Preconditions.checkArgument(request.hasTableId(), "TableId can't be empty");
          responseObserver.onNext(
              transactionToResponse(
                  prewriteTransaction(request.getCheckpointId(), request.getTableId())));
          break;
        case COMMIT:
          responseObserver.onNext(
              transactionToResponse(commitTransaction(request.getCheckpointId())));
          break;
        case ABORT:
          responseObserver.onNext(
              transactionToResponse(abortTransaction(request.getCheckpointId())));
          break;
        case GET:
          responseObserver.onNext(transactionToResponse(getTransaction(request.getCheckpointId())));
          break;
        default:
          throw new UnsupportedOperationException();
      }
    } catch (final Throwable t) {
      logger.error("Server RPC error", t);
      responseObserver.onError(t);
    } finally {
      responseObserver.onCompleted();
    }
  }

  @Override
  public void close() throws Exception {
    tiSession.close();
  }

  class TransactionHolder implements AutoCloseable {
    private volatile Transaction txn = null;
    private TwoPhaseCommitter committer = null;

    public Transaction getTxn() {
      return txn;
    }

    public void setTxn(Transaction txn) {
      this.txn = txn;
    }

    public TwoPhaseCommitter getCommitter() {
      if (committer == null) {
        committer = new TwoPhaseCommitter(tiSession, txn.getStartTs(), TXN_TTL_MS);
      }
      return committer;
    }

    @Override
    public void close() throws Exception {
      if (committer != null) {
        committer.close();
      }
    }

    @Override
    protected void finalize() throws Throwable {
      close();
    }
  }
}

```

**GrpcProvider.java**
```java
package cn.bestsign.binlogstream.tidb.coordinator.grpc;

import cn.bestsign.binlogstream.tidb.coordinator.Coordinator;
import cn.bestsign.binlogstream.tidb.coordinator.CoordinatorProvider;
import io.grpc.Server;
import io.grpc.ServerBuilder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.tikv.common.TiConfiguration;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.util.List;
import java.util.Random;
import java.util.stream.Collectors;

public class GrpcProvider implements CoordinatorProvider, AutoCloseable {
  private static Logger logger = LoggerFactory.getLogger(GrpcProvider.class);
  private static final int MAX_PORT_NUM = 20000;
  private static final int MIN_PORT_NUM = 10000;

  private final GrpcService service;
  private final Server server;

  public GrpcProvider(final int port, final TiConfiguration conf) {
    this.service = new GrpcService(conf);
    this.server = ServerBuilder.forPort(port).addService(service).build();
    try {
      logger.info("starting server at: {}", port);
      server.start();
    } catch (final IOException e) {
      throw new RuntimeException("Unable to start server", e);
    }
  }

  public GrpcProvider(final TiConfiguration conf) {
    this(getRandomPort(), conf);
  }

  @Override
  public Coordinator createCoordinator() {
    return new GrpcClient(getServerAddresses());
  }

  @Override
  public void close() throws Exception {
    server.shutdown();
  }

  public List<InetSocketAddress> getServerAddresses() {
    return server.getListenSockets().stream()
        .filter(s -> s instanceof InetSocketAddress)
        .map(s -> (InetSocketAddress) s)
        .filter(s -> s.getAddress().isAnyLocalAddress())
        .collect(Collectors.toList());
  }

  private static int getRandomPort() {
    final Random rand = new Random();
    return Math.abs(rand.nextInt()) % (MAX_PORT_NUM - MIN_PORT_NUM) + MIN_PORT_NUM;
  }
}

```

**Comment by ZhiXingHeYiApple** [comment]
I am confused that this project's version compatible with tikv. I want to use the cdc module, but not find usable document.

**Comment by marsishandsome** [comment]
Please try the example in README first https://github.com/tikv/client-java#create-a-rawkvclient.
CDC module is not stable.
