### ISSUE TITLE
[BUG] Error during multiIngest

### ISSUE THREAD

**Issue by marsishandsome** [tikv/client-java#268]
```
org.tikv.common.exception.GrpcException: message: "peer is not leader for region 1324, leader may Some(id: 1327 store_id: 4)"
not_leader {
  region_id: 1324
  leader {
    id: 1327
    store_id: 4
  }
}

	at org.tikv.common.importer.ImporterStoreClient.multiIngest(ImporterStoreClient.java:152)
	at org.tikv.common.importer.ImporterClient.ingest(ImporterClient.java:224)
	at org.tikv.common.importer.ImporterClient.write(ImporterClient.java:96)
	at org.tikv.bulkload.RawKVBulkLoader.writeAndIngest(RawKVBulkLoader.scala:152)
	at org.tikv.bulkload.RawKVBulkLoader.$anonfun$bulkLoad$5(RawKVBulkLoader.scala:110)
	at org.tikv.bulkload.RawKVBulkLoader.$anonfun$bulkLoad$5$adapted(RawKVBulkLoader.scala:109)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:994)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:994)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2154)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:463)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:466)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tisonkun** [comment]
> In the design doc https://github.com/tikv/rfcs/blob/master/text/0072-online-bulk-load-for-rawkv.md, one thing is missing.

You can always update the doc (along with the solution PR).

**Comment by peng1999** [comment]
Can this issue closed since all related PR have merged?
