### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by debjitk** [tikv/client-java#344]
The following error is occurring trying to connect to PD service

`java.lang.NoSuchMethodError: 'io.etcd.jetcd.ClientBuilder io.etcd.jetcd.ClientBuilder.endpoints(java.util.Collection)'`

Stack trace

```
java.lang.NoSuchMethodError: 'io.etcd.jetcd.ClientBuilder io.etcd.jetcd.ClientBuilder.endpoints(java.util.Collection)'

	at org.tikv.common.PDClient.initCluster(PDClient.java:566)
	at org.tikv.common.PDClient.<init>(PDClient.java:117)
	at org.tikv.common.PDClient.createRaw(PDClient.java:127)
	at org.tikv.common.TiSession.<init>(TiSession.java:76)
	at org.tikv.common.TiSession.create(TiSession.java:87)
	at co.riverlab.core.tikv.TiClient.<init>(TiClient.java:39)
	at co.riverlab.core.tikv.TiClient$Builder.build(TiClient.java:118)
```

**Comment by zz-jason** [comment]
could you provide the version of your client-java, pd, tikv and the reproduce code of this issue to help us to locate the root cause of it?
