### ISSUE TITLE
How to deal with this exception "java.lang.NoSuchFieldError: CONTEXT_SPAN_KEY"

### ISSUE THREAD

**Issue by bruceshao** [tikv/client-java#52]
java.lang.NoSuchFieldError: CONTEXT_SPAN_KEY

	at shade.io.grpc.internal.CensusTracingModule$TracingClientInterceptor.interceptCall(CensusTracingModule.java:327)
	at shade.io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:104)
	at shade.io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:551)
	at shade.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:113)
	at org.tikv.kvproto.PDGrpc$PDBlockingStub.getMembers(PDGrpc.java:898)
	at org.tikv.common.PDClient.getMembers(PDClient.java:260)
	at org.tikv.common.PDClient.initCluster(PDClient.java:346)
	at org.tikv.common.PDClient.createRaw(PDClient.java:378)
	at org.tikv.common.TiSession.<init>(TiSession.java:37)
	at org.tikv.common.TiSession.create(TiSession.java:45)

**Comment by birdstorm** [comment]
Would you please check the GRPC version you are using?

**Comment by anshulr** [comment]
Facing the same issue using grpc java 1.20.0

**Comment by birdstorm** [comment]
Maybe there is a conflict in grpc version. I will try to fix it by shading.

**Comment by trthhrtz** [comment]
@birdstorm any updates?

**Comment by trthhrtz** [comment]
@bruceshao @anshulr were you able to solve it?

**Comment by birdstorm** [comment]
A fix #74 was merged for this issue. @bruceshao you may try to build client-java with maven to get rid of this exception.
