### ISSUE TITLE
KvClient scan error

### ISSUE THREAD

**Issue by T-TRz879** [tikv/client-java#630]
i use this scan api
`scan(ByteString startKey, long version, int limit)`
code
`TiConfiguration conf = TiConfiguration.createDefault("127.0.0.1:2379");
    try (TiSession session = TiSession.create(conf)) {
      // two-phrase write
      long startTS = session.getTimestamp().getVersion();
      try (TwoPhaseCommitter twoPhaseCommitter = new TwoPhaseCommitter(session, startTS)) {
        BackOffer backOffer = ConcreteBackOffer.newCustomBackOff(1000);
        byte[] primaryKey = "key1".getBytes("UTF-8");
        byte[] key2 = "key2".getBytes("UTF-8");

        // first phrase: prewrite
        twoPhaseCommitter.prewritePrimaryKey(backOffer, primaryKey, "val1".getBytes("UTF-8"));
        List<BytePairWrapper> pairs = Arrays
                .asList(new BytePairWrapper(key2, "val2".getBytes("UTF-8")));
        twoPhaseCommitter.prewriteSecondaryKeys(primaryKey, pairs.iterator(), 1000);

        // second phrase: commit
        long commitTS = session.getTimestamp().getVersion();
        twoPhaseCommitter.commitPrimaryKey(backOffer, primaryKey, commitTS);
        List<ByteWrapper> keys = Arrays.asList(new ByteWrapper(key2));
        twoPhaseCommitter.commitSecondaryKeys(keys.iterator(), commitTS, 1000);
      }

      try (KVClient kvClient = session.createKVClient()) {
        long version = session.getTimestamp().getVersion();
        ByteString key1 = ByteString.copyFromUtf8("key1");
        ByteString key2 = ByteString.copyFromUtf8("key2");

        // get value of a single key
        ByteString val = kvClient.get(key1, version);
        System.out.println(val);

        // get value of multiple keys
        BackOffer backOffer = ConcreteBackOffer.newCustomBackOff(1000);
        List<Kvrpcpb.KvPair> kvPairs = kvClient.batchGet(backOffer, Arrays.asList(key1, key2), version);
        System.out.println(kvPairs);

        // get value of a range of keys
        kvPairs = kvClient.scan(key1, version,3);
        System.out.println(kvPairs);
      }
    }`

error

<ByteString@7ae0a9ec size=4 contents="val1">
[key: "key1"
value: "val1"
, key: "key2"
value: "val2"
]

org.tikv.common.exception.TiClientInternalException: Error scanning data from region.

	at org.tikv.common.operation.iterator.ScanIterator.cacheLoadFails(ScanIterator.java:113)
	at org.tikv.common.operation.iterator.ConcreteScanIterator.hasNext(ConcreteScanIterator.java:106)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at org.tikv.txn.KVClient.scan(KVClient.java:134)
	at fs.server.tikv.TikvScanTest.testTIKVTxn3(TikvScanTest.java:313)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:424)
	at java.util.ArrayList.get(ArrayList.java:437)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1311)
	at org.tikv.common.operation.iterator.ScanIterator.cacheLoadFails(ScanIterator.java:103)
	... 28 more

- Client Java: 3.3.0
- TiKV: 6.1.0

**Comment by T-TRz879** [comment]
@caniszczyk @niedhui @ @brson @kennytm  
i need help bro!

**Comment by T-TRz879** [comment]
@caniszczyk @niedhui @kennytm @brson
