### ISSUE TITLE
Failed to scatter region: 1264 use splitRegionAndScatter api

### ISSUE THREAD

**Issue by chaochaoyuyu19880105** [tikv/client-java#674]
### 1. Describe the bug

using session.splitRegionAndScatter api to split region  

### 2. Minimal reproduce step (Required)

Tikv has some imported data, and we want to import a new batch data, firstly we split the region

### 4. What did you expect to see? (Required)
do not Failed to scatter

### 5. What are your Java Client and TiKV versions? (Required)
3.3.0
- Client Java:
- TiKV:

**Comment by sunxiaoguang** [comment]
2022-11-25 12:26:53,867 INFO [org.tikv.common.TiSession] - start to split region id=2, split size=2
2022-11-25 12:26:53,873 INFO [org.tikv.common.TiSession] - region id=2, new region size=3
2022-11-25 12:26:53,873 INFO [org.tikv.common.TiSession] - splitRegion: return region size=3
2022-11-25 12:26:53,929 WARN [org.tikv.common.TiSession] - failed to scatter region: 42840
java.lang.IllegalArgumentException: Max sleep time cannot be less than 0.
        at org.tikv.shade.com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
        at org.tikv.common.util.ConcreteBackOffer.<init>(ConcreteBackOffer.java:62)
        at org.tikv.common.util.ConcreteBackOffer.newCustomBackOff(ConcreteBackOffer.java:93)
        at org.tikv.common.util.ConcreteBackOffer.newCustomBackOff(ConcreteBackOffer.java:97)
        at org.tikv.common.AbstractGRPCClient.checkHealth(AbstractGRPCClient.java:202)
        at org.tikv.common.PDClient.updateLeaderOrForwardFollower(PDClient.java:537)
        at org.tikv.common.operation.PDErrorHandler.handleResponseError(PDErrorHandler.java:62)
        at org.tikv.common.policy.RetryPolicy.callWithRetry(RetryPolicy.java:108)
        at org.tikv.common.AbstractGRPCClient.callWithRetry(AbstractGRPCClient.java:89)
        at org.tikv.common.PDClient.scatterRegion(PDClient.java:249)
        at org.tikv.common.TiSession.splitRegionAndScatter(TiSession.java:622)
        at org.tikv.common.TiSession.splitRegionAndScatter(TiSession.java:665)
        at com.fabarta.loader.client.tikv.TiKVClient.split(TiKVClient.java:348)
        at com.fabarta.loader.core.TiKVImporter.importData(TiKVImporter.java:54)
        at com.fabarta.loader.core.DumpResolverTask.flushBuffer(DumpResolverTask.java:98)
        at com.fabarta.loader.core.DumpResolverTask.run(DumpResolverTask.java:441)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
2022-11-25 12:26:53,930 INFO [org.tikv.common.TiSession] - start to wait scatter region finish
2022-11-25 12:26:53,931 INFO [org.tikv.common.PDClient] - wait scatter region on 42840 is finished
2022-11-25 12:26:53,951 INFO [org.tikv.common.PDClient] - wait scatter region 42844 at key 115,99,97,116,116,101,114,45,114,101,103,105,111,110 is RUNNING
2022-11-25 12:26:53,952 INFO [org.tikv.common.PDClient] - wait scatter region on 42844 is finished
2022-11-25 12:26:53,952 INFO [org.tikv.common.PDClient] - wait scatter region on 2 is finished
2022-11-25 12:26:53,952 INFO [org.tikv.common.TiSession] - splitRegionAndScatter cost 0 seconds

**Comment by sunxiaoguang** [comment]
It turns out that the real backoff timeout is a computed result of setTimeout. Using too large timeout may result in overflow internally which caused back offer to fail.
