### ISSUE TITLE
TwoPhase batch write error org.tikv.common.exception.TiBatchWriteException: Txn groupKeysByRegion error

### ISSUE THREAD

**Issue by chaochaoyuyu19880105** [tikv/client-java#675]
### 1. Describe the bug

we just use TwoPhaseWrite to add KVS

### 2. Minimal reproduce step (Required)

we just use TwoPhaseWrite to add KVS

### 3. What did you see instead (Required)
2022-11-22 23:45:06.673 [2pc-pool-0] [seekLeaderStore,256] WARN  o.t.c.r.AbstractRegionStoreClient - leader for region[44001] is not found, it is possible that network partition occurred
2022-11-22 23:45:06.674 [2pc-pool-0] [handleRequestError,245] WARN  o.t.c.operation.RegionErrorHandler - request failed because of: retry is exhausted.
2022-11-22 23:45:07.724 [2pc-pool-0] [canRetryAfterSleep,229] WARN  o.tikv.common.util.ConcreteBackOffer - BackOffer.maxSleep 1000ms is exceeded, errors:
2022-11-22 23:45:07.725 [2pc-pool-0] [logThrowError,257] WARN  o.tikv.common.util.ConcreteBackOffer - 
2.org.tikv.shade.io.grpc.StatusRuntimeException: UNAVAILABLE: not leader
3.org.tikv.shade.io.grpc.StatusRuntimeException: UNAVAILABLE: not leader
4.org.tikv.shade.io.grpc.StatusRuntimeException: UNAVAILABLE: not leader
2022-11-22 23:45:07.727 [metrics-fabarta-reporter-thread-1] [batchWrite,201] ERROR com.fabarta.client.TiKVClient - batchWrite error:
org.tikv.common.exception.TiBatchWriteException: Execution exception met.
        at org.tikv.txn.TwoPhaseCommitter.doPrewriteSecondaryKeys(TwoPhaseCommitter.java:308)
        at org.tikv.txn.TwoPhaseCommitter.prewriteSecondaryKeys(TwoPhaseCommitter.java:259)
        at com.fabarta.client.TiKVClient.batchWrite(TiKVClient.java:193)
        at com.fabarta.graph.cache.FabartaStorageManager.batchWrite(FabartaStorageManager.java:364)
        at com.fabarta.graph.structure.FabartaHelper.saveVertex(FabartaHelper.java:115)
        at com.fabarta.graph.structure.FabartaGraph.addVertex(FabartaGraph.java:237)
        at com.fabarta.metrics.FabartaReporter.createRecord(FabartaReporter.java:308)
        at com.fabarta.metrics.FabartaReporter.report(FabartaReporter.java:284)
        at com.fabarta.metrics.FabartaReporter.report(FabartaReporter.java:195)
        at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
        at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: org.tikv.common.exception.TiBatchWriteException: Txn groupKeysByRegion error
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.tikv.txn.TwoPhaseCommitter.doPrewriteSecondaryKeys(TwoPhaseCommitter.java:301)
        ... 16 common frames omitted
Caused by: org.tikv.common.exception.TiBatchWriteException: Txn groupKeysByRegion error
        at org.tikv.txn.TwoPhaseCommitter.groupKeysByRegion(TwoPhaseCommitter.java:635)
        at org.tikv.txn.TwoPhaseCommitter.doPrewriteSecondaryKeysInBatchesWithRetry(TwoPhaseCommitter.java:341)
        at org.tikv.txn.TwoPhaseCommitter.retryPrewriteBatch(TwoPhaseCommitter.java:390)
        at org.tikv.txn.TwoPhaseCommitter.doPrewriteSecondaryKeySingleBatchWithRetry(TwoPhaseCommitter.java:439)
        at org.tikv.txn.TwoPhaseCommitter.doPrewriteSecondaryKeysInBatchesWithRetry(TwoPhaseCommitter.java:357)
        at org.tikv.txn.TwoPhaseCommitter.lambda$doPrewriteSecondaryKeys$0(TwoPhaseCommitter.java:292)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        ... 3 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.tikv.common.region.RegionManager.getRegionStorePairByKey(RegionManager.java:185)
        at org.tikv.common.region.RegionManager.getRegionStorePairByKey(RegionManager.java:171)
        at org.tikv.txn.TwoPhaseCommitter.groupKeysByRegion(TwoPhaseCommitter.java:629)
        ... 11 common frames omitted

### 5. What are your Java Client and TiKV versions? (Required)
3.3.0
- Client Java:
- TiKV:

**Comment by sunxiaoguang** [comment]
This null pointer exception was fixed in 3.3.1, compile from tag or master can fix this issue.
