### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException: target

### ISSUE THREAD

**Issue by trthhrtz** [tikv/client-java#73]
Using this code:

```
package com.pv.app;
import org.tikv.common.TiConfiguration;
import org.tikv.common.TiSession;
import org.tikv.raw.RawKVClient;
import shade.com.google.common.base.Charsets;
import shade.com.google.protobuf.ByteString;
/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        System.out.println( "1" );
        TiConfiguration conf = TiConfiguration.createRawDefault("0.0.0.0:32798");
        System.out.println( "2" );
        TiSession session = TiSession.create(conf);
        System.out.println( "3" );
        RawKVClient client = session.createRawClient();
        System.out.println( "4" );
        client.put(ByteString.copyFrom("hello-key", Charsets.UTF_8), ByteString.copyFrom("hello-message", Charsets.UTF_8));
        System.out.println(client.get(ByteString.copyFrom("hello-key", Charsets.UTF_8)));
        System.out.println( "Hello World!" );
    }
}
```

I was unable to connect to tikv (without tidb). 

I was trying different ways of deploying and the errors were:

```
Exception in thread "main" java.lang.NullPointerException: target
        at shade.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
        at shade.io.grpc.internal.AbstractManagedChannelImplBuilder.<init>(AbstractManagedChannelImplBuilder.java:155)
        at shade.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:118)
        at shade.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:113)
        at shade.io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:99)
        at shade.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
        at shade.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
        at shade.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:36)
        at org.tikv.common.util.ChannelFactory.lambda$getChannel$0(ChannelFactory.java:45)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at org.tikv.common.util.ChannelFactory.getChannel(ChannelFactory.java:34)
        at org.tikv.common.PDClient.createLeaderWrapper(PDClient.java:287)
        at org.tikv.common.PDClient.initCluster(PDClient.java:356)
        at org.tikv.common.PDClient.createRaw(PDClient.java:378)
        at org.tikv.common.TiSession.<init>(TiSession.java:37)
        at org.tikv.common.TiSession.create(TiSession.java:45)
        at com.pv.app.App.main(App.java:22)
```

and 

```
Exception in thread "main" java.lang.NullPointerException: Failed to init client for PD cluster.
        at shade.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
        at org.tikv.common.PDClient.initCluster(PDClient.java:351)
        at org.tikv.common.PDClient.createRaw(PDClient.java:378)
        at org.tikv.common.TiSession.<init>(TiSession.java:37)
        at org.tikv.common.TiSession.create(TiSession.java:45)
        at com.pv.app.App.main(App.java:22)
```

**Comment by marsishandsome** [comment]
would u pls set `PD address and port` instead of `0.0.0.0:32798`?

**Comment by trthhrtz** [comment]
https://stackoverflow.com/questions/59358982/tikv-java-client-on-macos-failed-to-init-client-for-pd-cluster
