### ISSUE TITLE
LogExceptionRunnable throws when testing

### ISSUE THREAD

**Issue by zhuboshuai** [tikv/client-java#82]
the exception stack:
Jul 30, 2020 9:21:57 PM shade.io.grpc.internal.LogExceptionRunnable run
SEVERE: Exception while executing runnable shade.io.grpc.internal.ManagedChannelImpl$3@42c416c7
java.lang.NullPointerException: runnable is null
        at shade.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
        at shade.io.grpc.internal.ChannelExecutor.executeLater(ChannelExecutor.java:86)
        at shade.io.grpc.internal.ManagedChannelImpl$3.run(ManagedChannelImpl.java:340)
        at shade.io.grpc.internal.LogExceptionRunnable.run(LogExceptionRunnable.java:41)
        at shade.io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at shade.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
        at shade.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at shade.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at shade.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at shade.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at shade.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)

**Comment by liangyuanpeng** [comment]
Have any other message?
Some like: 

OS  
Client version
TiKV version

**Comment by zz-jason** [comment]
I'm going to close this issue. Feel free to reopen it If you meet the same issue again.
